apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: NodePort  # Change to LoadBalancer if you want a cloud load balancer
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
